-- AlterTable
ALTER TABLE "users" ALTER COLUMN "summoner_icon" DROP NOT NULL,
ALTER COLUMN "summoner_icon" DROP DEFAULT,
ALTER COLUMN "level" DROP NOT NULL,
ALTER COLUMN "rp" DROP NOT NULL,
ALTER COLUMN "essence" DROP NOT NULL,
ALTER COLUMN "percentage" DROP NOT NULL;
